api_url: "https://api.binance.com" # домен для запросов
timeout_seconds: 10  # задержка между проверкой цен на криптовалюту
convertation: "USDT" # валюта в которой показывать стоимость других валют (usdt~$)